// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
// ignore_for_file: type=lint
// ignore_for_file: invalid_use_of_protected_member
// ignore_for_file: unused_element, unnecessary_cast, override_on_non_overriding_member
// ignore_for_file: strict_raw_type, inference_failure_on_untyped_parameter

part of 'api_error_code.dart';

class ApiErrorCodeMapper extends EnumMapper<ApiErrorCode> {
  ApiErrorCodeMapper._();

  static ApiErrorCodeMapper? _instance;
  static ApiErrorCodeMapper ensureInitialized() {
    if (_instance == null) {
      MapperContainer.globals.use(_instance = ApiErrorCodeMapper._());
    }
    return _instance!;
  }

  static ApiErrorCode fromValue(dynamic value) {
    ensureInitialized();
    return MapperContainer.globals.fromValue(value);
  }

  @override
  ApiErrorCode decode(dynamic value) {
    switch (value) {
      case 'ACCESS_DENIED':
        return ApiErrorCode.accessDenied;
      case 'ACCOUNT_DISABLED':
        return ApiErrorCode.accountDisabled;
      case 'BAD_GATEWAY':
        return ApiErrorCode.badGateway;
      case 'BAD_REQUEST':
        return ApiErrorCode.badRequest;
      case 'BLUESKY_OAUTH_AUTHORIZATION_FAILED':
        return ApiErrorCode.blueskyOauthAuthorizationFailed;
      case 'BLUESKY_OAUTH_CALLBACK_FAILED':
        return ApiErrorCode.blueskyOauthCallbackFailed;
      case 'BLUESKY_OAUTH_NOT_ENABLED':
        return ApiErrorCode.blueskyOauthNotEnabled;
      case 'BLUESKY_OAUTH_SESSION_EXPIRED':
        return ApiErrorCode.blueskyOauthSessionExpired;
      case 'BLUESKY_OAUTH_STATE_INVALID':
        return ApiErrorCode.blueskyOauthStateInvalid;
      case 'ACCOUNT_SCHEDULED_FOR_DELETION':
        return ApiErrorCode.accountScheduledForDeletion;
      case 'ACCOUNT_SUSPENDED_PERMANENTLY':
        return ApiErrorCode.accountSuspendedPermanently;
      case 'ACCOUNT_SUSPENDED_TEMPORARILY':
        return ApiErrorCode.accountSuspendedTemporarily;
      case 'ACCOUNT_SUSPICIOUS_ACTIVITY':
        return ApiErrorCode.accountSuspiciousActivity;
      case 'ACCOUNT_TOO_NEW_FOR_GUILD':
        return ApiErrorCode.accountTooNewForGuild;
      case 'ACLS_MUST_BE_NON_EMPTY':
        return ApiErrorCode.aclsMustBeNonEmpty;
      case 'ADMIN_API_KEY_NOT_FOUND':
        return ApiErrorCode.adminApiKeyNotFound;
      case 'APPLICATION_NOT_FOUND':
        return ApiErrorCode.applicationNotFound;
      case 'APPLICATION_NOT_OWNED':
        return ApiErrorCode.applicationNotOwned;
      case 'ALREADY_FRIENDS':
        return ApiErrorCode.alreadyFriends;
      case 'AUDIT_LOG_INDEXING':
        return ApiErrorCode.auditLogIndexing;
      case 'BOTS_CANNOT_SEND_FRIEND_REQUESTS':
        return ApiErrorCode.botsCannotSendFriendRequests;
      case 'BOT_ALREADY_IN_GUILD':
        return ApiErrorCode.botAlreadyInGuild;
      case 'BOT_APPLICATION_NOT_FOUND':
        return ApiErrorCode.botApplicationNotFound;
      case 'BOT_IS_PRIVATE':
        return ApiErrorCode.botIsPrivate;
      case 'BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED':
        return ApiErrorCode.botUserAuthEndpointAccessDenied;
      case 'BOT_USER_AUTH_SESSION_CREATION_DENIED':
        return ApiErrorCode.botUserAuthSessionCreationDenied;
      case 'BOT_USER_GENERATION_FAILED':
        return ApiErrorCode.botUserGenerationFailed;
      case 'BOT_USER_NOT_FOUND':
        return ApiErrorCode.botUserNotFound;
      case 'CALL_ALREADY_EXISTS':
        return ApiErrorCode.callAlreadyExists;
      case 'CANNOT_EDIT_OTHER_USER_MESSAGE':
        return ApiErrorCode.cannotEditOtherUserMessage;
      case 'CANNOT_EXECUTE_ON_DM':
        return ApiErrorCode.cannotExecuteOnDm;
      case 'CANNOT_MODIFY_SYSTEM_WEBHOOK':
        return ApiErrorCode.cannotModifySystemWebhook;
      case 'CANNOT_MODIFY_VOICE_STATE':
        return ApiErrorCode.cannotModifyVoiceState;
      case 'CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY':
        return ApiErrorCode.cannotRedeemPlutoniumWithVisionary;
      case 'CANNOT_REPORT_OWN_GUILD':
        return ApiErrorCode.cannotReportOwnGuild;
      case 'CANNOT_REPORT_OWN_MESSAGE':
        return ApiErrorCode.cannotReportOwnMessage;
      case 'CANNOT_REPORT_YOURSELF':
        return ApiErrorCode.cannotReportYourself;
      case 'CANNOT_SEND_EMPTY_MESSAGE':
        return ApiErrorCode.cannotSendEmptyMessage;
      case 'CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER':
        return ApiErrorCode.cannotSendFriendRequestToBlockedUser;
      case 'CANNOT_SEND_FRIEND_REQUEST_TO_SELF':
        return ApiErrorCode.cannotSendFriendRequestToSelf;
      case 'CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL':
        return ApiErrorCode.cannotSendMessagesInNonTextChannel;
      case 'CANNOT_SEND_MESSAGES_TO_USER':
        return ApiErrorCode.cannotSendMessagesToUser;
      case 'CANNOT_TRANSFER_OWNERSHIP_TO_BOT':
        return ApiErrorCode.cannotTransferOwnershipToBot;
      case 'CANNOT_SHRINK_RESERVED_SLOTS':
        return ApiErrorCode.cannotShrinkReservedSlots;
      case 'CAPTCHA_REQUIRED':
        return ApiErrorCode.captchaRequired;
      case 'CHANNEL_INDEXING':
        return ApiErrorCode.channelIndexing;
      case 'COMMUNICATION_DISABLED':
        return ApiErrorCode.communicationDisabled;
      case 'CONNECTION_ALREADY_EXISTS':
        return ApiErrorCode.connectionAlreadyExists;
      case 'CONNECTION_INITIATION_TOKEN_INVALID':
        return ApiErrorCode.connectionInitiationTokenInvalid;
      case 'CONNECTION_INVALID_IDENTIFIER':
        return ApiErrorCode.connectionInvalidIdentifier;
      case 'CONNECTION_INVALID_TYPE':
        return ApiErrorCode.connectionInvalidType;
      case 'CONNECTION_LIMIT_REACHED':
        return ApiErrorCode.connectionLimitReached;
      case 'CONNECTION_NOT_FOUND':
        return ApiErrorCode.connectionNotFound;
      case 'CONNECTION_VERIFICATION_FAILED':
        return ApiErrorCode.connectionVerificationFailed;
      case 'CONFLICT':
        return ApiErrorCode.conflict;
      case 'CONTENT_BLOCKED':
        return ApiErrorCode.contentBlocked;
      case 'CREATION_FAILED':
        return ApiErrorCode.creationFailed;
      case 'CSAM_SCAN_FAILED':
        return ApiErrorCode.csamScanFailed;
      case 'CSAM_SCAN_PARSE_ERROR':
        return ApiErrorCode.csamScanParseError;
      case 'CSAM_SCAN_SUBSCRIPTION_ERROR':
        return ApiErrorCode.csamScanSubscriptionError;
      case 'CSAM_SCAN_TIMEOUT':
        return ApiErrorCode.csamScanTimeout;
      case 'DECRYPTION_FAILED':
        return ApiErrorCode.decryptionFailed;
      case 'DELETION_FAILED':
        return ApiErrorCode.deletionFailed;
      case 'DISCOVERY_ALREADY_APPLIED':
        return ApiErrorCode.discoveryAlreadyApplied;
      case 'DISCOVERY_APPLICATION_ALREADY_REVIEWED':
        return ApiErrorCode.discoveryApplicationAlreadyReviewed;
      case 'DISCOVERY_APPLICATION_NOT_FOUND':
        return ApiErrorCode.discoveryApplicationNotFound;
      case 'DISCOVERY_DESCRIPTION_REQUIRED':
        return ApiErrorCode.discoveryDescriptionRequired;
      case 'DISCOVERY_DISABLED':
        return ApiErrorCode.discoveryDisabled;
      case 'DISCOVERY_INSUFFICIENT_MEMBERS':
        return ApiErrorCode.discoveryInsufficientMembers;
      case 'DISCOVERY_INVALID_CATEGORY':
        return ApiErrorCode.discoveryInvalidCategory;
      case 'DISCOVERY_NOT_DISCOVERABLE':
        return ApiErrorCode.discoveryNotDiscoverable;
      case 'DISCRIMINATOR_REQUIRED':
        return ApiErrorCode.discriminatorRequired;
      case 'EMAIL_SERVICE_NOT_TESTABLE':
        return ApiErrorCode.emailServiceNotTestable;
      case 'EMAIL_VERIFICATION_REQUIRED':
        return ApiErrorCode.emailVerificationRequired;
      case 'EMPTY_ENCRYPTED_BODY':
        return ApiErrorCode.emptyEncryptedBody;
      case 'ENCRYPTION_FAILED':
        return ApiErrorCode.encryptionFailed;
      case 'EXPLICIT_CONTENT_CANNOT_BE_SENT':
        return ApiErrorCode.explicitContentCannotBeSent;
      case 'FEATURE_NOT_AVAILABLE_SELF_HOSTED':
        return ApiErrorCode.featureNotAvailableSelfHosted;
      case 'FEATURE_TEMPORARILY_DISABLED':
        return ApiErrorCode.featureTemporarilyDisabled;
      case 'FILE_SIZE_TOO_LARGE':
        return ApiErrorCode.fileSizeTooLarge;
      case 'FORBIDDEN':
        return ApiErrorCode.forbidden;
      case 'FRIEND_REQUEST_BLOCKED':
        return ApiErrorCode.friendRequestBlocked;
      case 'GATEWAY_TIMEOUT':
        return ApiErrorCode.gatewayTimeout;
      case 'GENERAL_ERROR':
        return ApiErrorCode.generalError;
      case 'GONE':
        return ApiErrorCode.gone;
      case 'GIFT_CODE_ALREADY_REDEEMED':
        return ApiErrorCode.giftCodeAlreadyRedeemed;
      case 'GUILD_PHONE_VERIFICATION_REQUIRED':
        return ApiErrorCode.guildPhoneVerificationRequired;
      case 'GUILD_VERIFICATION_REQUIRED':
        return ApiErrorCode.guildVerificationRequired;
      case 'HANDOFF_CODE_EXPIRED':
        return ApiErrorCode.handoffCodeExpired;
      case 'HARVEST_EXPIRED':
        return ApiErrorCode.harvestExpired;
      case 'HARVEST_FAILED':
        return ApiErrorCode.harvestFailed;
      case 'HARVEST_NOT_READY':
        return ApiErrorCode.harvestNotReady;
      case 'HARVEST_ON_COOLDOWN':
        return ApiErrorCode.harvestOnCooldown;
      case 'HTTP_GET_AUTHORIZE_NOT_SUPPORTED':
        return ApiErrorCode.httpGetAuthorizeNotSupported;
      case 'INSTANCE_VERSION_MISMATCH':
        return ApiErrorCode.instanceVersionMismatch;
      case 'INTERNAL_SERVER_ERROR':
        return ApiErrorCode.internalServerError;
      case 'INVALID_ACLS_FORMAT':
        return ApiErrorCode.invalidAclsFormat;
      case 'INVALID_API_ORIGIN':
        return ApiErrorCode.invalidApiOrigin;
      case 'INVALID_AUTH_TOKEN':
        return ApiErrorCode.invalidAuthToken;
      case 'INVALID_BOT_FLAG':
        return ApiErrorCode.invalidBotFlag;
      case 'INVALID_CAPTCHA':
        return ApiErrorCode.invalidCaptcha;
      case 'INVALID_CHANNEL_TYPE_FOR_CALL':
        return ApiErrorCode.invalidChannelTypeForCall;
      case 'INVALID_CHANNEL_TYPE':
        return ApiErrorCode.invalidChannelType;
      case 'INVALID_CLIENT':
        return ApiErrorCode.invalidClient;
      case 'INVALID_CLIENT_SECRET':
        return ApiErrorCode.invalidClientSecret;
      case 'INVALID_DSA_REPORT_TARGET':
        return ApiErrorCode.invalidDsaReportTarget;
      case 'INVALID_DSA_TICKET':
        return ApiErrorCode.invalidDsaTicket;
      case 'INVALID_DSA_VERIFICATION_CODE':
        return ApiErrorCode.invalidDsaVerificationCode;
      case 'INVALID_DECRYPTED_JSON':
        return ApiErrorCode.invalidDecryptedJson;
      case 'INVALID_EPHEMERAL_KEY':
        return ApiErrorCode.invalidEphemeralKey;
      case 'INVALID_FLAGS_FORMAT':
        return ApiErrorCode.invalidFlagsFormat;
      case 'INVALID_IV':
        return ApiErrorCode.invalidIv;
      case 'INVALID_FORM_BODY':
        return ApiErrorCode.invalidFormBody;
      case 'INVALID_GRANT':
        return ApiErrorCode.invalidGrant;
      case 'INVALID_HANDOFF_CODE':
        return ApiErrorCode.invalidHandoffCode;
      case 'INVALID_PACK_TYPE':
        return ApiErrorCode.invalidPackType;
      case 'INVALID_PERMISSIONS_INTEGER':
        return ApiErrorCode.invalidPermissionsInteger;
      case 'INVALID_PERMISSIONS_NEGATIVE':
        return ApiErrorCode.invalidPermissionsNegative;
      case 'INVALID_PHONE_NUMBER':
        return ApiErrorCode.invalidPhoneNumber;
      case 'INVALID_PHONE_VERIFICATION_CODE':
        return ApiErrorCode.invalidPhoneVerificationCode;
      case 'INVALID_REDIRECT_URI':
        return ApiErrorCode.invalidRedirectUri;
      case 'INVALID_REQUEST':
        return ApiErrorCode.invalidRequest;
      case 'INVALID_RESPONSE_TYPE_FOR_NON_BOT':
        return ApiErrorCode.invalidResponseTypeForNonBot;
      case 'INVALID_SCOPE':
        return ApiErrorCode.invalidScope;
      case 'INVALID_STREAM_KEY_FORMAT':
        return ApiErrorCode.invalidStreamKeyFormat;
      case 'INVALID_STREAM_THUMBNAIL_PAYLOAD':
        return ApiErrorCode.invalidStreamThumbnailPayload;
      case 'INVALID_SUDO_TOKEN':
        return ApiErrorCode.invalidSudoToken;
      case 'INVALID_SUSPICIOUS_FLAGS_FORMAT':
        return ApiErrorCode.invalidSuspiciousFlagsFormat;
      case 'INVALID_SYSTEM_FLAG':
        return ApiErrorCode.invalidSystemFlag;
      case 'INVALID_TIMESTAMP':
        return ApiErrorCode.invalidTimestamp;
      case 'INVALID_TOKEN':
        return ApiErrorCode.invalidToken;
      case 'INVALID_WEBAUTHN_AUTHENTICATION_COUNTER':
        return ApiErrorCode.invalidWebauthnAuthenticationCounter;
      case 'INVALID_WEBAUTHN_CREDENTIAL_COUNTER':
        return ApiErrorCode.invalidWebauthnCredentialCounter;
      case 'INVALID_WEBAUTHN_CREDENTIAL':
        return ApiErrorCode.invalidWebauthnCredential;
      case 'INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT':
        return ApiErrorCode.invalidWebauthnPublicKeyFormat;
      case 'INVITES_DISABLED':
        return ApiErrorCode.invitesDisabled;
      case 'IP_AUTHORIZATION_REQUIRED':
        return ApiErrorCode.ipAuthorizationRequired;
      case 'IP_AUTHORIZATION_RESEND_COOLDOWN':
        return ApiErrorCode.ipAuthorizationResendCooldown;
      case 'IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED':
        return ApiErrorCode.ipAuthorizationResendLimitExceeded;
      case 'IP_BANNED':
        return ApiErrorCode.ipBanned;
      case 'MAX_ANIMATED_EMOJIS':
        return ApiErrorCode.maxAnimatedEmojis;
      case 'MAX_BOOKMARKS':
        return ApiErrorCode.maxBookmarks;
      case 'MAX_CATEGORY_CHANNELS':
        return ApiErrorCode.maxCategoryChannels;
      case 'MAX_EMOJIS':
        return ApiErrorCode.maxEmojis;
      case 'MAX_FAVORITE_MEMES':
        return ApiErrorCode.maxFavoriteMemes;
      case 'MAX_FRIENDS':
        return ApiErrorCode.maxFriends;
      case 'MAX_GROUP_DM_RECIPIENTS':
        return ApiErrorCode.maxGroupDmRecipients;
      case 'MAX_GROUP_DMS':
        return ApiErrorCode.maxGroupDms;
      case 'MAX_GUILD_CHANNELS':
        return ApiErrorCode.maxGuildChannels;
      case 'MAX_GUILD_MEMBERS':
        return ApiErrorCode.maxGuildMembers;
      case 'MAX_GUILD_ROLES':
        return ApiErrorCode.maxGuildRoles;
      case 'MAX_GUILDS':
        return ApiErrorCode.maxGuilds;
      case 'MAX_INVITES':
        return ApiErrorCode.maxInvites;
      case 'MAX_PACK_EXPRESSIONS':
        return ApiErrorCode.maxPackExpressions;
      case 'MAX_PACKS':
        return ApiErrorCode.maxPacks;
      case 'MAX_PINS_PER_CHANNEL':
        return ApiErrorCode.maxPinsPerChannel;
      case 'MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE':
        return ApiErrorCode.messageTotalAttachmentSizeTooLarge;
      case 'MAX_REACTIONS':
        return ApiErrorCode.maxReactions;
      case 'MAX_STICKERS':
        return ApiErrorCode.maxStickers;
      case 'MAX_WEBHOOKS_PER_CHANNEL':
        return ApiErrorCode.maxWebhooksPerChannel;
      case 'MAX_WEBHOOKS_PER_GUILD':
        return ApiErrorCode.maxWebhooksPerGuild;
      case 'MAX_WEBHOOKS':
        return ApiErrorCode.maxWebhooks;
      case 'NCMEC_ALREADY_SUBMITTED':
        return ApiErrorCode.ncmecAlreadySubmitted;
      case 'NCMEC_SUBMISSION_FAILED':
        return ApiErrorCode.ncmecSubmissionFailed;
      case 'MEDIA_METADATA_ERROR':
        return ApiErrorCode.mediaMetadataError;
      case 'METHOD_NOT_ALLOWED':
        return ApiErrorCode.methodNotAllowed;
      case 'MISSING_ACCESS':
        return ApiErrorCode.missingAccess;
      case 'MISSING_ACL':
        return ApiErrorCode.missingAcl;
      case 'MISSING_AUTHORIZATION':
        return ApiErrorCode.missingAuthorization;
      case 'MISSING_CLIENT_SECRET':
        return ApiErrorCode.missingClientSecret;
      case 'MISSING_EPHEMERAL_KEY':
        return ApiErrorCode.missingEphemeralKey;
      case 'MISSING_IV':
        return ApiErrorCode.missingIv;
      case 'MISSING_OAUTH_ADMIN_SCOPE':
        return ApiErrorCode.missingOauthAdminScope;
      case 'MISSING_OAUTH_FIELDS':
        return ApiErrorCode.missingOauthFields;
      case 'MISSING_OAUTH_SCOPE':
        return ApiErrorCode.missingOauthScope;
      case 'MISSING_PERMISSIONS':
        return ApiErrorCode.missingPermissions;
      case 'MISSING_REDIRECT_URI':
        return ApiErrorCode.missingRedirectUri;
      case 'NO_ACTIVE_CALL':
        return ApiErrorCode.noActiveCall;
      case 'NO_ACTIVE_SUBSCRIPTION':
        return ApiErrorCode.noActiveSubscription;
      case 'NOT_FOUND':
        return ApiErrorCode.notFound;
      case 'NOT_IMPLEMENTED':
        return ApiErrorCode.notImplemented;
      case 'NO_PASSKEYS_REGISTERED':
        return ApiErrorCode.noPasskeysRegistered;
      case 'NO_PENDING_DELETION':
        return ApiErrorCode.noPendingDeletion;
      case 'NO_USERS_WITH_FLUXERTAG_EXIST':
        return ApiErrorCode.noUsersWithFluxertagExist;
      case 'NO_VISIONARY_SLOTS_AVAILABLE':
        return ApiErrorCode.noVisionarySlotsAvailable;
      case 'NOT_A_BOT_APPLICATION':
        return ApiErrorCode.notABotApplication;
      case 'NOT_FRIENDS_WITH_USER':
        return ApiErrorCode.notFriendsWithUser;
      case 'NOT_OWNER_OF_ADMIN_API_KEY':
        return ApiErrorCode.notOwnerOfAdminApiKey;
      case 'NSFW_CONTENT_AGE_RESTRICTED':
        return ApiErrorCode.nsfwContentAgeRestricted;
      case 'PACK_ACCESS_DENIED':
        return ApiErrorCode.packAccessDenied;
      case 'PASSKEY_AUTHENTICATION_FAILED':
        return ApiErrorCode.passkeyAuthenticationFailed;
      case 'PASSKEYS_DISABLED':
        return ApiErrorCode.passkeysDisabled;
      case 'PHONE_ALREADY_USED':
        return ApiErrorCode.phoneAlreadyUsed;
      case 'PHONE_RATE_LIMIT_EXCEEDED':
        return ApiErrorCode.phoneRateLimitExceeded;
      case 'PHONE_REQUIRED_FOR_SMS_MFA':
        return ApiErrorCode.phoneRequiredForSmsMfa;
      case 'PHONE_VERIFICATION_REQUIRED':
        return ApiErrorCode.phoneVerificationRequired;
      case 'PREMIUM_PURCHASE_BLOCKED':
        return ApiErrorCode.premiumPurchaseBlocked;
      case 'PREVIEW_MUST_BE_JPEG':
        return ApiErrorCode.previewMustBeJpeg;
      case 'PROCESSING_FAILED':
        return ApiErrorCode.processingFailed;
      case 'RATE_LIMITED':
        return ApiErrorCode.rateLimited;
      case 'REDIRECT_URI_REQUIRED_FOR_NON_BOT':
        return ApiErrorCode.redirectUriRequiredForNonBot;
      case 'REPORT_ALREADY_RESOLVED':
        return ApiErrorCode.reportAlreadyResolved;
      case 'REPORT_BANNED':
        return ApiErrorCode.reportBanned;
      case 'RESPONSE_VALIDATION_ERROR':
        return ApiErrorCode.responseValidationError;
      case 'SERVICE_UNAVAILABLE':
        return ApiErrorCode.serviceUnavailable;
      case 'SESSION_TOKEN_MISMATCH':
        return ApiErrorCode.sessionTokenMismatch;
      case 'SLOWMODE_RATE_LIMITED':
        return ApiErrorCode.slowmodeRateLimited;
      case 'SMS_MFA_NOT_ENABLED':
        return ApiErrorCode.smsMfaNotEnabled;
      case 'SMS_MFA_REQUIRES_TOTP':
        return ApiErrorCode.smsMfaRequiresTotp;
      case 'SMS_VERIFICATION_UNAVAILABLE':
        return ApiErrorCode.smsVerificationUnavailable;
      case 'SSO_REQUIRED':
        return ApiErrorCode.ssoRequired;
      case 'STREAM_KEY_CHANNEL_MISMATCH':
        return ApiErrorCode.streamKeyChannelMismatch;
      case 'STREAM_KEY_SCOPE_MISMATCH':
        return ApiErrorCode.streamKeyScopeMismatch;
      case 'STREAM_THUMBNAIL_PAYLOAD_EMPTY':
        return ApiErrorCode.streamThumbnailPayloadEmpty;
      case 'STRIPE_ERROR':
        return ApiErrorCode.stripeError;
      case 'STRIPE_GIFT_REDEMPTION_IN_PROGRESS':
        return ApiErrorCode.stripeGiftRedemptionInProgress;
      case 'STRIPE_INVALID_PRODUCT':
        return ApiErrorCode.stripeInvalidProduct;
      case 'STRIPE_INVALID_PRODUCT_CONFIGURATION':
        return ApiErrorCode.stripeInvalidProductConfiguration;
      case 'STRIPE_NO_ACTIVE_SUBSCRIPTION':
        return ApiErrorCode.stripeNoActiveSubscription;
      case 'STRIPE_NO_PURCHASE_HISTORY':
        return ApiErrorCode.stripeNoPurchaseHistory;
      case 'STRIPE_NO_SUBSCRIPTION':
        return ApiErrorCode.stripeNoSubscription;
      case 'STRIPE_PAYMENT_NOT_AVAILABLE':
        return ApiErrorCode.stripePaymentNotAvailable;
      case 'STRIPE_SUBSCRIPTION_ALREADY_CANCELING':
        return ApiErrorCode.stripeSubscriptionAlreadyCanceling;
      case 'STRIPE_SUBSCRIPTION_NOT_CANCELING':
        return ApiErrorCode.stripeSubscriptionNotCanceling;
      case 'STRIPE_SUBSCRIPTION_PERIOD_END_MISSING':
        return ApiErrorCode.stripeSubscriptionPeriodEndMissing;
      case 'STRIPE_WEBHOOK_NOT_AVAILABLE':
        return ApiErrorCode.stripeWebhookNotAvailable;
      case 'STRIPE_WEBHOOK_SIGNATURE_INVALID':
        return ApiErrorCode.stripeWebhookSignatureInvalid;
      case 'STRIPE_WEBHOOK_SIGNATURE_MISSING':
        return ApiErrorCode.stripeWebhookSignatureMissing;
      case 'DONATION_AMOUNT_INVALID':
        return ApiErrorCode.donationAmountInvalid;
      case 'DONATION_MAGIC_LINK_EXPIRED':
        return ApiErrorCode.donationMagicLinkExpired;
      case 'DONATION_MAGIC_LINK_INVALID':
        return ApiErrorCode.donationMagicLinkInvalid;
      case 'DONATION_MAGIC_LINK_USED':
        return ApiErrorCode.donationMagicLinkUsed;
      case 'DONOR_NOT_FOUND':
        return ApiErrorCode.donorNotFound;
      case 'SUDO_MODE_REQUIRED':
        return ApiErrorCode.sudoModeRequired;
      case 'TAG_ALREADY_TAKEN':
        return ApiErrorCode.tagAlreadyTaken;
      case 'TEMPORARY_INVITE_REQUIRES_PRESENCE':
        return ApiErrorCode.temporaryInviteRequiresPresence;
      case 'TEST_HARNESS_DISABLED':
        return ApiErrorCode.testHarnessDisabled;
      case 'TEST_HARNESS_FORBIDDEN':
        return ApiErrorCode.testHarnessForbidden;
      case 'TWO_FA_NOT_ENABLED':
        return ApiErrorCode.twoFaNotEnabled;
      case 'TWO_FACTOR_REQUIRED':
        return ApiErrorCode.twoFactorRequired;
      case 'UNAUTHORIZED':
        return ApiErrorCode.unauthorized;
      case 'UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS':
        return ApiErrorCode.unclaimedAccountCannotAcceptFriendRequests;
      case 'UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS':
        return ApiErrorCode.unclaimedAccountCannotAddReactions;
      case 'UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS':
        return ApiErrorCode.unclaimedAccountCannotCreateApplications;
      case 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS':
        return ApiErrorCode.unclaimedAccountCannotJoinGroupDms;
      case 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS':
        return ApiErrorCode.unclaimedAccountCannotJoinOneOnOneVoiceCalls;
      case 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS':
        return ApiErrorCode.unclaimedAccountCannotJoinVoiceChannels;
      case 'UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES':
        return ApiErrorCode.unclaimedAccountCannotMakePurchases;
      case 'UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES':
        return ApiErrorCode.unclaimedAccountCannotSendDirectMessages;
      case 'UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS':
        return ApiErrorCode.unclaimedAccountCannotSendFriendRequests;
      case 'UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES':
        return ApiErrorCode.unclaimedAccountCannotSendMessages;
      case 'UNKNOWN_CHANNEL':
        return ApiErrorCode.unknownChannel;
      case 'UNKNOWN_EMOJI':
        return ApiErrorCode.unknownEmoji;
      case 'UNKNOWN_FAVORITE_MEME':
        return ApiErrorCode.unknownFavoriteMeme;
      case 'UNKNOWN_GIFT_CODE':
        return ApiErrorCode.unknownGiftCode;
      case 'UNKNOWN_GUILD':
        return ApiErrorCode.unknownGuild;
      case 'UNKNOWN_HARVEST':
        return ApiErrorCode.unknownHarvest;
      case 'UNKNOWN_INVITE':
        return ApiErrorCode.unknownInvite;
      case 'UNKNOWN_MEMBER':
        return ApiErrorCode.unknownMember;
      case 'UNKNOWN_MESSAGE':
        return ApiErrorCode.unknownMessage;
      case 'UNKNOWN_PACK':
        return ApiErrorCode.unknownPack;
      case 'UNKNOWN_REPORT':
        return ApiErrorCode.unknownReport;
      case 'UNKNOWN_ROLE':
        return ApiErrorCode.unknownRole;
      case 'UNKNOWN_STICKER':
        return ApiErrorCode.unknownSticker;
      case 'UNKNOWN_SUSPICIOUS_FLAG':
        return ApiErrorCode.unknownSuspiciousFlag;
      case 'UNKNOWN_USER_FLAG':
        return ApiErrorCode.unknownUserFlag;
      case 'UNKNOWN_USER':
        return ApiErrorCode.unknownUser;
      case 'UNKNOWN_VOICE_REGION':
        return ApiErrorCode.unknownVoiceRegion;
      case 'UNKNOWN_VOICE_SERVER':
        return ApiErrorCode.unknownVoiceServer;
      case 'UNKNOWN_WEBAUTHN_CREDENTIAL':
        return ApiErrorCode.unknownWebauthnCredential;
      case 'UNKNOWN_APPLICATION':
        return ApiErrorCode.unknownApplication;
      case 'UNKNOWN_WEBHOOK':
        return ApiErrorCode.unknownWebhook;
      case 'UNSUPPORTED_RESPONSE_TYPE':
        return ApiErrorCode.unsupportedResponseType;
      case 'USERNAME_NOT_AVAILABLE':
        return ApiErrorCode.usernameNotAvailable;
      case 'UPDATE_FAILED':
        return ApiErrorCode.updateFailed;
      case 'USER_BANNED_FROM_GUILD':
        return ApiErrorCode.userBannedFromGuild;
      case 'USER_IP_BANNED_FROM_GUILD':
        return ApiErrorCode.userIpBannedFromGuild;
      case 'USER_NOT_IN_VOICE':
        return ApiErrorCode.userNotInVoice;
      case 'USER_OWNS_GUILDS':
        return ApiErrorCode.userOwnsGuilds;
      case 'VALIDATION_ERROR':
        return ApiErrorCode.validationError;
      case 'VOICE_CHANNEL_FULL':
        return ApiErrorCode.voiceChannelFull;
      case 'WEBAUTHN_CREDENTIAL_LIMIT_REACHED':
        return ApiErrorCode.webauthnCredentialLimitReached;
      case 'unknown':
        return ApiErrorCode.unknown;
      default:
        throw MapperException.unknownEnumValue(value);
    }
  }

  @override
  dynamic encode(ApiErrorCode self) {
    switch (self) {
      case ApiErrorCode.accessDenied:
        return 'ACCESS_DENIED';
      case ApiErrorCode.accountDisabled:
        return 'ACCOUNT_DISABLED';
      case ApiErrorCode.badGateway:
        return 'BAD_GATEWAY';
      case ApiErrorCode.badRequest:
        return 'BAD_REQUEST';
      case ApiErrorCode.blueskyOauthAuthorizationFailed:
        return 'BLUESKY_OAUTH_AUTHORIZATION_FAILED';
      case ApiErrorCode.blueskyOauthCallbackFailed:
        return 'BLUESKY_OAUTH_CALLBACK_FAILED';
      case ApiErrorCode.blueskyOauthNotEnabled:
        return 'BLUESKY_OAUTH_NOT_ENABLED';
      case ApiErrorCode.blueskyOauthSessionExpired:
        return 'BLUESKY_OAUTH_SESSION_EXPIRED';
      case ApiErrorCode.blueskyOauthStateInvalid:
        return 'BLUESKY_OAUTH_STATE_INVALID';
      case ApiErrorCode.accountScheduledForDeletion:
        return 'ACCOUNT_SCHEDULED_FOR_DELETION';
      case ApiErrorCode.accountSuspendedPermanently:
        return 'ACCOUNT_SUSPENDED_PERMANENTLY';
      case ApiErrorCode.accountSuspendedTemporarily:
        return 'ACCOUNT_SUSPENDED_TEMPORARILY';
      case ApiErrorCode.accountSuspiciousActivity:
        return 'ACCOUNT_SUSPICIOUS_ACTIVITY';
      case ApiErrorCode.accountTooNewForGuild:
        return 'ACCOUNT_TOO_NEW_FOR_GUILD';
      case ApiErrorCode.aclsMustBeNonEmpty:
        return 'ACLS_MUST_BE_NON_EMPTY';
      case ApiErrorCode.adminApiKeyNotFound:
        return 'ADMIN_API_KEY_NOT_FOUND';
      case ApiErrorCode.applicationNotFound:
        return 'APPLICATION_NOT_FOUND';
      case ApiErrorCode.applicationNotOwned:
        return 'APPLICATION_NOT_OWNED';
      case ApiErrorCode.alreadyFriends:
        return 'ALREADY_FRIENDS';
      case ApiErrorCode.auditLogIndexing:
        return 'AUDIT_LOG_INDEXING';
      case ApiErrorCode.botsCannotSendFriendRequests:
        return 'BOTS_CANNOT_SEND_FRIEND_REQUESTS';
      case ApiErrorCode.botAlreadyInGuild:
        return 'BOT_ALREADY_IN_GUILD';
      case ApiErrorCode.botApplicationNotFound:
        return 'BOT_APPLICATION_NOT_FOUND';
      case ApiErrorCode.botIsPrivate:
        return 'BOT_IS_PRIVATE';
      case ApiErrorCode.botUserAuthEndpointAccessDenied:
        return 'BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED';
      case ApiErrorCode.botUserAuthSessionCreationDenied:
        return 'BOT_USER_AUTH_SESSION_CREATION_DENIED';
      case ApiErrorCode.botUserGenerationFailed:
        return 'BOT_USER_GENERATION_FAILED';
      case ApiErrorCode.botUserNotFound:
        return 'BOT_USER_NOT_FOUND';
      case ApiErrorCode.callAlreadyExists:
        return 'CALL_ALREADY_EXISTS';
      case ApiErrorCode.cannotEditOtherUserMessage:
        return 'CANNOT_EDIT_OTHER_USER_MESSAGE';
      case ApiErrorCode.cannotExecuteOnDm:
        return 'CANNOT_EXECUTE_ON_DM';
      case ApiErrorCode.cannotModifySystemWebhook:
        return 'CANNOT_MODIFY_SYSTEM_WEBHOOK';
      case ApiErrorCode.cannotModifyVoiceState:
        return 'CANNOT_MODIFY_VOICE_STATE';
      case ApiErrorCode.cannotRedeemPlutoniumWithVisionary:
        return 'CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY';
      case ApiErrorCode.cannotReportOwnGuild:
        return 'CANNOT_REPORT_OWN_GUILD';
      case ApiErrorCode.cannotReportOwnMessage:
        return 'CANNOT_REPORT_OWN_MESSAGE';
      case ApiErrorCode.cannotReportYourself:
        return 'CANNOT_REPORT_YOURSELF';
      case ApiErrorCode.cannotSendEmptyMessage:
        return 'CANNOT_SEND_EMPTY_MESSAGE';
      case ApiErrorCode.cannotSendFriendRequestToBlockedUser:
        return 'CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER';
      case ApiErrorCode.cannotSendFriendRequestToSelf:
        return 'CANNOT_SEND_FRIEND_REQUEST_TO_SELF';
      case ApiErrorCode.cannotSendMessagesInNonTextChannel:
        return 'CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL';
      case ApiErrorCode.cannotSendMessagesToUser:
        return 'CANNOT_SEND_MESSAGES_TO_USER';
      case ApiErrorCode.cannotTransferOwnershipToBot:
        return 'CANNOT_TRANSFER_OWNERSHIP_TO_BOT';
      case ApiErrorCode.cannotShrinkReservedSlots:
        return 'CANNOT_SHRINK_RESERVED_SLOTS';
      case ApiErrorCode.captchaRequired:
        return 'CAPTCHA_REQUIRED';
      case ApiErrorCode.channelIndexing:
        return 'CHANNEL_INDEXING';
      case ApiErrorCode.communicationDisabled:
        return 'COMMUNICATION_DISABLED';
      case ApiErrorCode.connectionAlreadyExists:
        return 'CONNECTION_ALREADY_EXISTS';
      case ApiErrorCode.connectionInitiationTokenInvalid:
        return 'CONNECTION_INITIATION_TOKEN_INVALID';
      case ApiErrorCode.connectionInvalidIdentifier:
        return 'CONNECTION_INVALID_IDENTIFIER';
      case ApiErrorCode.connectionInvalidType:
        return 'CONNECTION_INVALID_TYPE';
      case ApiErrorCode.connectionLimitReached:
        return 'CONNECTION_LIMIT_REACHED';
      case ApiErrorCode.connectionNotFound:
        return 'CONNECTION_NOT_FOUND';
      case ApiErrorCode.connectionVerificationFailed:
        return 'CONNECTION_VERIFICATION_FAILED';
      case ApiErrorCode.conflict:
        return 'CONFLICT';
      case ApiErrorCode.contentBlocked:
        return 'CONTENT_BLOCKED';
      case ApiErrorCode.creationFailed:
        return 'CREATION_FAILED';
      case ApiErrorCode.csamScanFailed:
        return 'CSAM_SCAN_FAILED';
      case ApiErrorCode.csamScanParseError:
        return 'CSAM_SCAN_PARSE_ERROR';
      case ApiErrorCode.csamScanSubscriptionError:
        return 'CSAM_SCAN_SUBSCRIPTION_ERROR';
      case ApiErrorCode.csamScanTimeout:
        return 'CSAM_SCAN_TIMEOUT';
      case ApiErrorCode.decryptionFailed:
        return 'DECRYPTION_FAILED';
      case ApiErrorCode.deletionFailed:
        return 'DELETION_FAILED';
      case ApiErrorCode.discoveryAlreadyApplied:
        return 'DISCOVERY_ALREADY_APPLIED';
      case ApiErrorCode.discoveryApplicationAlreadyReviewed:
        return 'DISCOVERY_APPLICATION_ALREADY_REVIEWED';
      case ApiErrorCode.discoveryApplicationNotFound:
        return 'DISCOVERY_APPLICATION_NOT_FOUND';
      case ApiErrorCode.discoveryDescriptionRequired:
        return 'DISCOVERY_DESCRIPTION_REQUIRED';
      case ApiErrorCode.discoveryDisabled:
        return 'DISCOVERY_DISABLED';
      case ApiErrorCode.discoveryInsufficientMembers:
        return 'DISCOVERY_INSUFFICIENT_MEMBERS';
      case ApiErrorCode.discoveryInvalidCategory:
        return 'DISCOVERY_INVALID_CATEGORY';
      case ApiErrorCode.discoveryNotDiscoverable:
        return 'DISCOVERY_NOT_DISCOVERABLE';
      case ApiErrorCode.discriminatorRequired:
        return 'DISCRIMINATOR_REQUIRED';
      case ApiErrorCode.emailServiceNotTestable:
        return 'EMAIL_SERVICE_NOT_TESTABLE';
      case ApiErrorCode.emailVerificationRequired:
        return 'EMAIL_VERIFICATION_REQUIRED';
      case ApiErrorCode.emptyEncryptedBody:
        return 'EMPTY_ENCRYPTED_BODY';
      case ApiErrorCode.encryptionFailed:
        return 'ENCRYPTION_FAILED';
      case ApiErrorCode.explicitContentCannotBeSent:
        return 'EXPLICIT_CONTENT_CANNOT_BE_SENT';
      case ApiErrorCode.featureNotAvailableSelfHosted:
        return 'FEATURE_NOT_AVAILABLE_SELF_HOSTED';
      case ApiErrorCode.featureTemporarilyDisabled:
        return 'FEATURE_TEMPORARILY_DISABLED';
      case ApiErrorCode.fileSizeTooLarge:
        return 'FILE_SIZE_TOO_LARGE';
      case ApiErrorCode.forbidden:
        return 'FORBIDDEN';
      case ApiErrorCode.friendRequestBlocked:
        return 'FRIEND_REQUEST_BLOCKED';
      case ApiErrorCode.gatewayTimeout:
        return 'GATEWAY_TIMEOUT';
      case ApiErrorCode.generalError:
        return 'GENERAL_ERROR';
      case ApiErrorCode.gone:
        return 'GONE';
      case ApiErrorCode.giftCodeAlreadyRedeemed:
        return 'GIFT_CODE_ALREADY_REDEEMED';
      case ApiErrorCode.guildPhoneVerificationRequired:
        return 'GUILD_PHONE_VERIFICATION_REQUIRED';
      case ApiErrorCode.guildVerificationRequired:
        return 'GUILD_VERIFICATION_REQUIRED';
      case ApiErrorCode.handoffCodeExpired:
        return 'HANDOFF_CODE_EXPIRED';
      case ApiErrorCode.harvestExpired:
        return 'HARVEST_EXPIRED';
      case ApiErrorCode.harvestFailed:
        return 'HARVEST_FAILED';
      case ApiErrorCode.harvestNotReady:
        return 'HARVEST_NOT_READY';
      case ApiErrorCode.harvestOnCooldown:
        return 'HARVEST_ON_COOLDOWN';
      case ApiErrorCode.httpGetAuthorizeNotSupported:
        return 'HTTP_GET_AUTHORIZE_NOT_SUPPORTED';
      case ApiErrorCode.instanceVersionMismatch:
        return 'INSTANCE_VERSION_MISMATCH';
      case ApiErrorCode.internalServerError:
        return 'INTERNAL_SERVER_ERROR';
      case ApiErrorCode.invalidAclsFormat:
        return 'INVALID_ACLS_FORMAT';
      case ApiErrorCode.invalidApiOrigin:
        return 'INVALID_API_ORIGIN';
      case ApiErrorCode.invalidAuthToken:
        return 'INVALID_AUTH_TOKEN';
      case ApiErrorCode.invalidBotFlag:
        return 'INVALID_BOT_FLAG';
      case ApiErrorCode.invalidCaptcha:
        return 'INVALID_CAPTCHA';
      case ApiErrorCode.invalidChannelTypeForCall:
        return 'INVALID_CHANNEL_TYPE_FOR_CALL';
      case ApiErrorCode.invalidChannelType:
        return 'INVALID_CHANNEL_TYPE';
      case ApiErrorCode.invalidClient:
        return 'INVALID_CLIENT';
      case ApiErrorCode.invalidClientSecret:
        return 'INVALID_CLIENT_SECRET';
      case ApiErrorCode.invalidDsaReportTarget:
        return 'INVALID_DSA_REPORT_TARGET';
      case ApiErrorCode.invalidDsaTicket:
        return 'INVALID_DSA_TICKET';
      case ApiErrorCode.invalidDsaVerificationCode:
        return 'INVALID_DSA_VERIFICATION_CODE';
      case ApiErrorCode.invalidDecryptedJson:
        return 'INVALID_DECRYPTED_JSON';
      case ApiErrorCode.invalidEphemeralKey:
        return 'INVALID_EPHEMERAL_KEY';
      case ApiErrorCode.invalidFlagsFormat:
        return 'INVALID_FLAGS_FORMAT';
      case ApiErrorCode.invalidIv:
        return 'INVALID_IV';
      case ApiErrorCode.invalidFormBody:
        return 'INVALID_FORM_BODY';
      case ApiErrorCode.invalidGrant:
        return 'INVALID_GRANT';
      case ApiErrorCode.invalidHandoffCode:
        return 'INVALID_HANDOFF_CODE';
      case ApiErrorCode.invalidPackType:
        return 'INVALID_PACK_TYPE';
      case ApiErrorCode.invalidPermissionsInteger:
        return 'INVALID_PERMISSIONS_INTEGER';
      case ApiErrorCode.invalidPermissionsNegative:
        return 'INVALID_PERMISSIONS_NEGATIVE';
      case ApiErrorCode.invalidPhoneNumber:
        return 'INVALID_PHONE_NUMBER';
      case ApiErrorCode.invalidPhoneVerificationCode:
        return 'INVALID_PHONE_VERIFICATION_CODE';
      case ApiErrorCode.invalidRedirectUri:
        return 'INVALID_REDIRECT_URI';
      case ApiErrorCode.invalidRequest:
        return 'INVALID_REQUEST';
      case ApiErrorCode.invalidResponseTypeForNonBot:
        return 'INVALID_RESPONSE_TYPE_FOR_NON_BOT';
      case ApiErrorCode.invalidScope:
        return 'INVALID_SCOPE';
      case ApiErrorCode.invalidStreamKeyFormat:
        return 'INVALID_STREAM_KEY_FORMAT';
      case ApiErrorCode.invalidStreamThumbnailPayload:
        return 'INVALID_STREAM_THUMBNAIL_PAYLOAD';
      case ApiErrorCode.invalidSudoToken:
        return 'INVALID_SUDO_TOKEN';
      case ApiErrorCode.invalidSuspiciousFlagsFormat:
        return 'INVALID_SUSPICIOUS_FLAGS_FORMAT';
      case ApiErrorCode.invalidSystemFlag:
        return 'INVALID_SYSTEM_FLAG';
      case ApiErrorCode.invalidTimestamp:
        return 'INVALID_TIMESTAMP';
      case ApiErrorCode.invalidToken:
        return 'INVALID_TOKEN';
      case ApiErrorCode.invalidWebauthnAuthenticationCounter:
        return 'INVALID_WEBAUTHN_AUTHENTICATION_COUNTER';
      case ApiErrorCode.invalidWebauthnCredentialCounter:
        return 'INVALID_WEBAUTHN_CREDENTIAL_COUNTER';
      case ApiErrorCode.invalidWebauthnCredential:
        return 'INVALID_WEBAUTHN_CREDENTIAL';
      case ApiErrorCode.invalidWebauthnPublicKeyFormat:
        return 'INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT';
      case ApiErrorCode.invitesDisabled:
        return 'INVITES_DISABLED';
      case ApiErrorCode.ipAuthorizationRequired:
        return 'IP_AUTHORIZATION_REQUIRED';
      case ApiErrorCode.ipAuthorizationResendCooldown:
        return 'IP_AUTHORIZATION_RESEND_COOLDOWN';
      case ApiErrorCode.ipAuthorizationResendLimitExceeded:
        return 'IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED';
      case ApiErrorCode.ipBanned:
        return 'IP_BANNED';
      case ApiErrorCode.maxAnimatedEmojis:
        return 'MAX_ANIMATED_EMOJIS';
      case ApiErrorCode.maxBookmarks:
        return 'MAX_BOOKMARKS';
      case ApiErrorCode.maxCategoryChannels:
        return 'MAX_CATEGORY_CHANNELS';
      case ApiErrorCode.maxEmojis:
        return 'MAX_EMOJIS';
      case ApiErrorCode.maxFavoriteMemes:
        return 'MAX_FAVORITE_MEMES';
      case ApiErrorCode.maxFriends:
        return 'MAX_FRIENDS';
      case ApiErrorCode.maxGroupDmRecipients:
        return 'MAX_GROUP_DM_RECIPIENTS';
      case ApiErrorCode.maxGroupDms:
        return 'MAX_GROUP_DMS';
      case ApiErrorCode.maxGuildChannels:
        return 'MAX_GUILD_CHANNELS';
      case ApiErrorCode.maxGuildMembers:
        return 'MAX_GUILD_MEMBERS';
      case ApiErrorCode.maxGuildRoles:
        return 'MAX_GUILD_ROLES';
      case ApiErrorCode.maxGuilds:
        return 'MAX_GUILDS';
      case ApiErrorCode.maxInvites:
        return 'MAX_INVITES';
      case ApiErrorCode.maxPackExpressions:
        return 'MAX_PACK_EXPRESSIONS';
      case ApiErrorCode.maxPacks:
        return 'MAX_PACKS';
      case ApiErrorCode.maxPinsPerChannel:
        return 'MAX_PINS_PER_CHANNEL';
      case ApiErrorCode.messageTotalAttachmentSizeTooLarge:
        return 'MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE';
      case ApiErrorCode.maxReactions:
        return 'MAX_REACTIONS';
      case ApiErrorCode.maxStickers:
        return 'MAX_STICKERS';
      case ApiErrorCode.maxWebhooksPerChannel:
        return 'MAX_WEBHOOKS_PER_CHANNEL';
      case ApiErrorCode.maxWebhooksPerGuild:
        return 'MAX_WEBHOOKS_PER_GUILD';
      case ApiErrorCode.maxWebhooks:
        return 'MAX_WEBHOOKS';
      case ApiErrorCode.ncmecAlreadySubmitted:
        return 'NCMEC_ALREADY_SUBMITTED';
      case ApiErrorCode.ncmecSubmissionFailed:
        return 'NCMEC_SUBMISSION_FAILED';
      case ApiErrorCode.mediaMetadataError:
        return 'MEDIA_METADATA_ERROR';
      case ApiErrorCode.methodNotAllowed:
        return 'METHOD_NOT_ALLOWED';
      case ApiErrorCode.missingAccess:
        return 'MISSING_ACCESS';
      case ApiErrorCode.missingAcl:
        return 'MISSING_ACL';
      case ApiErrorCode.missingAuthorization:
        return 'MISSING_AUTHORIZATION';
      case ApiErrorCode.missingClientSecret:
        return 'MISSING_CLIENT_SECRET';
      case ApiErrorCode.missingEphemeralKey:
        return 'MISSING_EPHEMERAL_KEY';
      case ApiErrorCode.missingIv:
        return 'MISSING_IV';
      case ApiErrorCode.missingOauthAdminScope:
        return 'MISSING_OAUTH_ADMIN_SCOPE';
      case ApiErrorCode.missingOauthFields:
        return 'MISSING_OAUTH_FIELDS';
      case ApiErrorCode.missingOauthScope:
        return 'MISSING_OAUTH_SCOPE';
      case ApiErrorCode.missingPermissions:
        return 'MISSING_PERMISSIONS';
      case ApiErrorCode.missingRedirectUri:
        return 'MISSING_REDIRECT_URI';
      case ApiErrorCode.noActiveCall:
        return 'NO_ACTIVE_CALL';
      case ApiErrorCode.noActiveSubscription:
        return 'NO_ACTIVE_SUBSCRIPTION';
      case ApiErrorCode.notFound:
        return 'NOT_FOUND';
      case ApiErrorCode.notImplemented:
        return 'NOT_IMPLEMENTED';
      case ApiErrorCode.noPasskeysRegistered:
        return 'NO_PASSKEYS_REGISTERED';
      case ApiErrorCode.noPendingDeletion:
        return 'NO_PENDING_DELETION';
      case ApiErrorCode.noUsersWithFluxertagExist:
        return 'NO_USERS_WITH_FLUXERTAG_EXIST';
      case ApiErrorCode.noVisionarySlotsAvailable:
        return 'NO_VISIONARY_SLOTS_AVAILABLE';
      case ApiErrorCode.notABotApplication:
        return 'NOT_A_BOT_APPLICATION';
      case ApiErrorCode.notFriendsWithUser:
        return 'NOT_FRIENDS_WITH_USER';
      case ApiErrorCode.notOwnerOfAdminApiKey:
        return 'NOT_OWNER_OF_ADMIN_API_KEY';
      case ApiErrorCode.nsfwContentAgeRestricted:
        return 'NSFW_CONTENT_AGE_RESTRICTED';
      case ApiErrorCode.packAccessDenied:
        return 'PACK_ACCESS_DENIED';
      case ApiErrorCode.passkeyAuthenticationFailed:
        return 'PASSKEY_AUTHENTICATION_FAILED';
      case ApiErrorCode.passkeysDisabled:
        return 'PASSKEYS_DISABLED';
      case ApiErrorCode.phoneAlreadyUsed:
        return 'PHONE_ALREADY_USED';
      case ApiErrorCode.phoneRateLimitExceeded:
        return 'PHONE_RATE_LIMIT_EXCEEDED';
      case ApiErrorCode.phoneRequiredForSmsMfa:
        return 'PHONE_REQUIRED_FOR_SMS_MFA';
      case ApiErrorCode.phoneVerificationRequired:
        return 'PHONE_VERIFICATION_REQUIRED';
      case ApiErrorCode.premiumPurchaseBlocked:
        return 'PREMIUM_PURCHASE_BLOCKED';
      case ApiErrorCode.previewMustBeJpeg:
        return 'PREVIEW_MUST_BE_JPEG';
      case ApiErrorCode.processingFailed:
        return 'PROCESSING_FAILED';
      case ApiErrorCode.rateLimited:
        return 'RATE_LIMITED';
      case ApiErrorCode.redirectUriRequiredForNonBot:
        return 'REDIRECT_URI_REQUIRED_FOR_NON_BOT';
      case ApiErrorCode.reportAlreadyResolved:
        return 'REPORT_ALREADY_RESOLVED';
      case ApiErrorCode.reportBanned:
        return 'REPORT_BANNED';
      case ApiErrorCode.responseValidationError:
        return 'RESPONSE_VALIDATION_ERROR';
      case ApiErrorCode.serviceUnavailable:
        return 'SERVICE_UNAVAILABLE';
      case ApiErrorCode.sessionTokenMismatch:
        return 'SESSION_TOKEN_MISMATCH';
      case ApiErrorCode.slowmodeRateLimited:
        return 'SLOWMODE_RATE_LIMITED';
      case ApiErrorCode.smsMfaNotEnabled:
        return 'SMS_MFA_NOT_ENABLED';
      case ApiErrorCode.smsMfaRequiresTotp:
        return 'SMS_MFA_REQUIRES_TOTP';
      case ApiErrorCode.smsVerificationUnavailable:
        return 'SMS_VERIFICATION_UNAVAILABLE';
      case ApiErrorCode.ssoRequired:
        return 'SSO_REQUIRED';
      case ApiErrorCode.streamKeyChannelMismatch:
        return 'STREAM_KEY_CHANNEL_MISMATCH';
      case ApiErrorCode.streamKeyScopeMismatch:
        return 'STREAM_KEY_SCOPE_MISMATCH';
      case ApiErrorCode.streamThumbnailPayloadEmpty:
        return 'STREAM_THUMBNAIL_PAYLOAD_EMPTY';
      case ApiErrorCode.stripeError:
        return 'STRIPE_ERROR';
      case ApiErrorCode.stripeGiftRedemptionInProgress:
        return 'STRIPE_GIFT_REDEMPTION_IN_PROGRESS';
      case ApiErrorCode.stripeInvalidProduct:
        return 'STRIPE_INVALID_PRODUCT';
      case ApiErrorCode.stripeInvalidProductConfiguration:
        return 'STRIPE_INVALID_PRODUCT_CONFIGURATION';
      case ApiErrorCode.stripeNoActiveSubscription:
        return 'STRIPE_NO_ACTIVE_SUBSCRIPTION';
      case ApiErrorCode.stripeNoPurchaseHistory:
        return 'STRIPE_NO_PURCHASE_HISTORY';
      case ApiErrorCode.stripeNoSubscription:
        return 'STRIPE_NO_SUBSCRIPTION';
      case ApiErrorCode.stripePaymentNotAvailable:
        return 'STRIPE_PAYMENT_NOT_AVAILABLE';
      case ApiErrorCode.stripeSubscriptionAlreadyCanceling:
        return 'STRIPE_SUBSCRIPTION_ALREADY_CANCELING';
      case ApiErrorCode.stripeSubscriptionNotCanceling:
        return 'STRIPE_SUBSCRIPTION_NOT_CANCELING';
      case ApiErrorCode.stripeSubscriptionPeriodEndMissing:
        return 'STRIPE_SUBSCRIPTION_PERIOD_END_MISSING';
      case ApiErrorCode.stripeWebhookNotAvailable:
        return 'STRIPE_WEBHOOK_NOT_AVAILABLE';
      case ApiErrorCode.stripeWebhookSignatureInvalid:
        return 'STRIPE_WEBHOOK_SIGNATURE_INVALID';
      case ApiErrorCode.stripeWebhookSignatureMissing:
        return 'STRIPE_WEBHOOK_SIGNATURE_MISSING';
      case ApiErrorCode.donationAmountInvalid:
        return 'DONATION_AMOUNT_INVALID';
      case ApiErrorCode.donationMagicLinkExpired:
        return 'DONATION_MAGIC_LINK_EXPIRED';
      case ApiErrorCode.donationMagicLinkInvalid:
        return 'DONATION_MAGIC_LINK_INVALID';
      case ApiErrorCode.donationMagicLinkUsed:
        return 'DONATION_MAGIC_LINK_USED';
      case ApiErrorCode.donorNotFound:
        return 'DONOR_NOT_FOUND';
      case ApiErrorCode.sudoModeRequired:
        return 'SUDO_MODE_REQUIRED';
      case ApiErrorCode.tagAlreadyTaken:
        return 'TAG_ALREADY_TAKEN';
      case ApiErrorCode.temporaryInviteRequiresPresence:
        return 'TEMPORARY_INVITE_REQUIRES_PRESENCE';
      case ApiErrorCode.testHarnessDisabled:
        return 'TEST_HARNESS_DISABLED';
      case ApiErrorCode.testHarnessForbidden:
        return 'TEST_HARNESS_FORBIDDEN';
      case ApiErrorCode.twoFaNotEnabled:
        return 'TWO_FA_NOT_ENABLED';
      case ApiErrorCode.twoFactorRequired:
        return 'TWO_FACTOR_REQUIRED';
      case ApiErrorCode.unauthorized:
        return 'UNAUTHORIZED';
      case ApiErrorCode.unclaimedAccountCannotAcceptFriendRequests:
        return 'UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS';
      case ApiErrorCode.unclaimedAccountCannotAddReactions:
        return 'UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS';
      case ApiErrorCode.unclaimedAccountCannotCreateApplications:
        return 'UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS';
      case ApiErrorCode.unclaimedAccountCannotJoinGroupDms:
        return 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS';
      case ApiErrorCode.unclaimedAccountCannotJoinOneOnOneVoiceCalls:
        return 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS';
      case ApiErrorCode.unclaimedAccountCannotJoinVoiceChannels:
        return 'UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS';
      case ApiErrorCode.unclaimedAccountCannotMakePurchases:
        return 'UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES';
      case ApiErrorCode.unclaimedAccountCannotSendDirectMessages:
        return 'UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES';
      case ApiErrorCode.unclaimedAccountCannotSendFriendRequests:
        return 'UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS';
      case ApiErrorCode.unclaimedAccountCannotSendMessages:
        return 'UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES';
      case ApiErrorCode.unknownChannel:
        return 'UNKNOWN_CHANNEL';
      case ApiErrorCode.unknownEmoji:
        return 'UNKNOWN_EMOJI';
      case ApiErrorCode.unknownFavoriteMeme:
        return 'UNKNOWN_FAVORITE_MEME';
      case ApiErrorCode.unknownGiftCode:
        return 'UNKNOWN_GIFT_CODE';
      case ApiErrorCode.unknownGuild:
        return 'UNKNOWN_GUILD';
      case ApiErrorCode.unknownHarvest:
        return 'UNKNOWN_HARVEST';
      case ApiErrorCode.unknownInvite:
        return 'UNKNOWN_INVITE';
      case ApiErrorCode.unknownMember:
        return 'UNKNOWN_MEMBER';
      case ApiErrorCode.unknownMessage:
        return 'UNKNOWN_MESSAGE';
      case ApiErrorCode.unknownPack:
        return 'UNKNOWN_PACK';
      case ApiErrorCode.unknownReport:
        return 'UNKNOWN_REPORT';
      case ApiErrorCode.unknownRole:
        return 'UNKNOWN_ROLE';
      case ApiErrorCode.unknownSticker:
        return 'UNKNOWN_STICKER';
      case ApiErrorCode.unknownSuspiciousFlag:
        return 'UNKNOWN_SUSPICIOUS_FLAG';
      case ApiErrorCode.unknownUserFlag:
        return 'UNKNOWN_USER_FLAG';
      case ApiErrorCode.unknownUser:
        return 'UNKNOWN_USER';
      case ApiErrorCode.unknownVoiceRegion:
        return 'UNKNOWN_VOICE_REGION';
      case ApiErrorCode.unknownVoiceServer:
        return 'UNKNOWN_VOICE_SERVER';
      case ApiErrorCode.unknownWebauthnCredential:
        return 'UNKNOWN_WEBAUTHN_CREDENTIAL';
      case ApiErrorCode.unknownApplication:
        return 'UNKNOWN_APPLICATION';
      case ApiErrorCode.unknownWebhook:
        return 'UNKNOWN_WEBHOOK';
      case ApiErrorCode.unsupportedResponseType:
        return 'UNSUPPORTED_RESPONSE_TYPE';
      case ApiErrorCode.usernameNotAvailable:
        return 'USERNAME_NOT_AVAILABLE';
      case ApiErrorCode.updateFailed:
        return 'UPDATE_FAILED';
      case ApiErrorCode.userBannedFromGuild:
        return 'USER_BANNED_FROM_GUILD';
      case ApiErrorCode.userIpBannedFromGuild:
        return 'USER_IP_BANNED_FROM_GUILD';
      case ApiErrorCode.userNotInVoice:
        return 'USER_NOT_IN_VOICE';
      case ApiErrorCode.userOwnsGuilds:
        return 'USER_OWNS_GUILDS';
      case ApiErrorCode.validationError:
        return 'VALIDATION_ERROR';
      case ApiErrorCode.voiceChannelFull:
        return 'VOICE_CHANNEL_FULL';
      case ApiErrorCode.webauthnCredentialLimitReached:
        return 'WEBAUTHN_CREDENTIAL_LIMIT_REACHED';
      case ApiErrorCode.unknown:
        return 'unknown';
    }
  }
}

extension ApiErrorCodeMapperExtension on ApiErrorCode {
  dynamic toValue() {
    ApiErrorCodeMapper.ensureInitialized();
    return MapperContainer.globals.toValue<ApiErrorCode>(this);
  }
}

